spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/manager_system?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
#    password: 643f28cdeada47c4
    password: 643f28cdeada47c4
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.zero.system.entity,com.zero.system.entity.*.*
  mapper-locations: classpath:mapper/*.xml,classpath:mapper/*/.xml
#server:
#  port: 8089

